language: go
go:
- 1.9
install:
- go get -t ./...
- make install-linters
script:
- make check
notifications:
  slack:
    secure: KT8ru7EHSsCtL9WLvKC9d0+qibwBlIptvckHZMM64G/FIeOcaXBMcF15CBtYkYViGaa/rzjVIlJie1BUtFaGzN+7Qn5sMdZGo8DIPdkZnSBlII95kSPItqP+dAsQaZZp4mJeawJRUIHzpTtzOvTwrONsPUVh6PKMkdE/EtDLxalJ3hYMLt4/A/mgOfImqIwp/LTtiMcVDNnUX+ySe5qqrnlZwqjSUdzd5t/FPMH6cre7gbq7x8kFqtn1FCYEYlaO9uf+1kFNGjD99nX4IBRTadCR9ekU4QeH0kkFELAE4shRpQ20F2JM26mS7JvF3C3C44H4dSYdzbJEO4P4u30hNfosKbgCt2v3WpEsRIjq6aLX0ZXNb0l/xR+zmhKXUS+X5KSZeG46J5MdTdQjSXk/i/EWVqf/wBjGEiCdeiEl85y9J/zz26ON19tOB8HGneOX7GbNc4Es2LjclpptoqL/WnEynyPFBfUVqEynj6zAd4pSyoHwDtpbNdSqY+dADIxmmZqNxBynSUXY8sY9c77H6EIvgayEOQL1uPSPOtXouuHZrAjNhkO6HEHLOeGeX/LyJr0gnhBE5lJAH5EM5vsJ+OhwRQV/YHr6kswXB4c3C8+4S2Zn0k6lpp9HI89svLAp8U/6kXbSYnJ3vhhjQ0jVAtSAEw7xIM7y+d/8ff20EHs=
